### ISSUE TITLE
Hello！ Question about the language.

### ISSUE THREAD

**Issue by Codefmeister** [Deopster/Mercenaries-Hearthstone-game-bot#1]
I read this code briefly this morning and I am really curious about this.
Seems that this is based on opencv.
So if I want to use this, the Hearthstones' language option should be Ruassian?
Or I should change pictures into my own language?

**Comment by Deopster** [comment]
Great, I'll add support on the screens FullHD in about 2 hours and if it doesn't help, I think I'll need your help in adding Chinese.

**Comment by RomanKhoilo** [comment]
Hi, there/Привет.
 
Registered on github just to get notifications on your project progress. Could help with testing (rus/eng only).
Sent you request in discord if you don't mind.

**Comment by Deopster** [comment]
Да, конечно, буду рад любой помощи, добавил в друзья. Вечером созвонимся.
