### ISSUE TITLE
[Feature Request] use pynput instead of AHK

### ISSUE THREAD

**Issue by Efemache** [Deopster/Mercenaries-Hearthstone-game-bot#16]
Hi,

I use Linux and AHK doesn't work (no AHK for Linux, others libraries needed or Wine needed and possibly a lot of headaches).
Could you use pynput ? https://pypi.org/project/pynput/

It works for Linux, MacOS and Windows : 
https://pynput.readthedocs.io/en/latest/limitations.html

Regards

**Comment by Efemache** [comment]
Linux support is coming. 
2 pull requests added on exDev branch (last one : https://github.com/Deopster/Mercenaries-Hearthstone-game-bot/pull/20)

The next one (the third) should do the work

**Comment by Deopster** [comment]
> Hi,
> 
> I use Linux and AHK doesn't work (no AHK for Linux, others libraries needed or Wine needed and possibly a lot of headaches). Could you use pynput ? https://pypi.org/project/pynput/
> 
> It works for Linux, MacOS and Windows : https://pynput.readthedocs.io/en/latest/limitations.html
> 
> Regards

Hey dude, i just returned to work on this project and checked out what exactly you did. And this is such a big rework of my project, thank you very much.

**Comment by Efemache** [comment]
> 
> Hey dude, i just returned to work on this project and checked out what exactly you did. And this is such a big rework of my project, thank you very much.

The pleasure was mine :) 

Linux is supported; I close the issue.
