### ISSUE TITLE
Bot doesnt start up

### ISSUE THREAD

**Issue by rosanod351** [Deopster/Mercenaries-Hearthstone-game-bot#30]
Bot doenst start up.
Any Advice?

C:\Users\Marku\Downloads\Mercenaries-Hearthstone-game-bot-main\Mercenaries-Hearthstone-game-bot-main>pip install --user -r requirements.txt
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
Requirement already satisfied: ahk==0.13.0 in c:\users\marku\appdata\roaming\python\python38\site-packages (from -r requirements.txt (line 1)) (0.13.0)
Requirement already satisfied: ahk-binary==1.1.33.9 in c:\users\marku\appdata\roaming\python\python38\site-packages (from -r requirements.txt (line 2)) (1.1.33.9)
Requirement already satisfied: cachetools==4.2.4 in c:\users\marku\appdata\roaming\python\python38\site-packages (from -r requirements.txt (line 3)) (4.2.4)
Requirement already satisfied: configparser==5.0.2 in c:\users\marku\appdata\roaming\python\python38\site-packages (from -r requirements.txt (line 4)) (5.0.2)
Requirement already satisfied: future==0.18.2 in c:\users\marku\appdata\roaming\python\python38\site-packages (from -r requirements.txt (line 5)) (0.18.2)
Requirement already satisfied: Jinja2==3.0.2 in c:\users\marku\appdata\roaming\python\python38\site-packages (from -r requirements.txt (line 6)) (3.0.2)
Requirement already satisfied: keyboard==0.13.5 in c:\users\marku\appdata\roaming\python\python38\site-packages (from -r requirements.txt (line 7)) (0.13.5)
Requirement already satisfied: MarkupSafe==2.0.1 in c:\users\marku\appdata\roaming\python\python38\site-packages (from -r requirements.txt (line 8)) (2.0.1)
Requirement already satisfied: mss==6.1.0 in c:\users\marku\appdata\roaming\python\python38\site-packages (from -r requirements.txt (line 9)) (6.1.0)
Requirement already satisfied: numpy==1.21.2 in c:\users\marku\appdata\roaming\python\python38\site-packages (from -r requirements.txt (line 10)) (1.21.2)
Requirement already satisfied: opencv-python==4.5.3.56 in c:\users\marku\appdata\roaming\python\python38\site-packages (from -r requirements.txt (line 11)) (4.5.3.56)
Requirement already satisfied: pefile==2021.9.3 in c:\users\marku\appdata\roaming\python\python38\site-packages (from -r requirements.txt (line 12)) (2021.9.3)
Requirement already satisfied: Pillow==8.4.0 in c:\users\marku\appdata\roaming\python\python38\site-packages (from -r requirements.txt (line 13)) (8.4.0)
Requirement already satisfied: python-dotenv==0.19.1 in c:\users\marku\appdata\roaming\python\python38\site-packages (from -r requirements.txt (line 14)) (0.19.1)
Requirement already satisfied: pyautogui==0.9.53 in c:\users\marku\appdata\roaming\python\python38\site-packages (from -r requirements.txt (line 15)) (0.9.53)
Requirement already satisfied: pymsgbox in c:\users\marku\appdata\roaming\python\python38\site-packages (from pyautogui==0.9.53->-r requirements.txt (line 15)) (1.0.9)
Requirement already satisfied: PyTweening>=1.0.1 in c:\users\marku\appdata\roaming\python\python38\site-packages (from pyautogui==0.9.53->-r requirements.txt (line 15)) (1.0.3)
Requirement already satisfied: pyscreeze>=0.1.21 in c:\users\marku\appdata\roaming\python\python38\site-packages (from pyautogui==0.9.53->-r requirements.txt (line 15)) (0.1.27)
Requirement already satisfied: pygetwindow>=0.0.5 in c:\users\marku\appdata\roaming\python\python38\site-packages (from pyautogui==0.9.53->-r requirements.txt (line 15)) (0.0.9)
Requirement already satisfied: mouseinfo in c:\users\marku\appdata\roaming\python\python38\site-packages (from pyautogui==0.9.53->-r requirements.txt (line 15)) (0.1.3)
Requirement already satisfied: pyrect in c:\users\marku\appdata\roaming\python\python38\site-packages (from pygetwindow>=0.0.5->pyautogui==0.9.53->-r requirements.txt (line 15)) (0.1.4)
Requirement already satisfied: pyperclip in c:\users\marku\appdata\roaming\python\python38\site-packages (from mouseinfo->pyautogui==0.9.53->-r requirements.txt (line 15)) (1.8.2)

C:\Users\Marku\Downloads\Mercenaries-Hearthstone-game-bot-main\Mercenaries-Hearthstone-game-bot-main>main.py
Traceback (most recent call last):
  File "C:\Users\Marku\Downloads\Mercenaries-Hearthstone-game-bot-main\Mercenaries-Hearthstone-game-bot-main\main.py", line 23, in <module>
    ahk = AHK()
  File "C:\Users\Marku\AppData\Roaming\Python\Python38\site-packages\ahk\window.py", line 667, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\Marku\AppData\Roaming\Python\Python38\site-packages\ahk\mouse.py", line 60, in __init__
    super().__init__(**kwargs)
  File "C:\Users\Marku\AppData\Roaming\Python\Python38\site-packages\ahk\gui.py", line 12, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\Marku\AppData\Roaming\Python\Python38\site-packages\ahk\script.py", line 88, in __init__
    self.executable_path = _resolve_executable_path(executable_path)
  File "C:\Users\Marku\AppData\Roaming\Python\Python38\site-packages\ahk\script.py", line 46, in _resolve_executable_path
    raise ExecutableNotFoundError(
ahk.script.ExecutableNotFoundError: Could not find AutoHotkey.exe on PATH. Provide the absolute path with the `executable_path` keyword argument or in the AHK_PATH environment variable. You may be able to resolve this error by installing the binary extra: pip install "ahk[binary]"

C:\Users\Marku\Downloads\Mercenaries-Hearthstone-game-bot-main\Mercenaries-Hearthstone-game-bot-main>pause

**Comment by Efemache** [comment]
Hi,

"ahk.script.ExecutableNotFoundError: Could not find AutoHotkey.exe on PATH"
You have to install AHK : AutoHotKey

**Comment by rosanod351** [comment]
Works, Thank  You
